Update the generate command
Mezatsong/laravel-swagger-docs pull request #11
Opened 2023-11-24 17:06 UTC by evertramos

It seems the command has been updated to `php artisan swagger:generate`

2023-11-28 08:21 UTC, Mezatsong requested changes

2023-11-28 08:21 UTC, Mezatsong commented on README.md
>  If you wish to generate docs for a subset of your routes, you can pass a filter using `--filter`, for example: `php artisan laravel-swagger:generate --filter="/api"`
Update the example below too please

2023-11-29 14:20 UTC, evertramos commented on README.md
>  If you wish to generate docs for a subset of your routes, you can pass a filter using `--filter`, for example: `php artisan laravel-swagger:generate --filter="/api"`
done!

2023-11-30 06:12 UTC, Mezatsong approved these changes

2023-11-30 06:13 UTC, merged